'use strict';

/**
 * Command risk rules for Claude Code PreToolUse hook.
 * Each rule has: pattern (RegExp), name, ja (Japanese desc), en (English desc).
 * Matched top-down; first match wins within each level.
 */
module.exports = {
  high: [
    // --- File system destruction ---
    { pattern: /^rm\s+.*(-r|-rf|-fr|--recursive)/, name: 'rm -rf',
      ja: 'ファイル/ディレクトリを再帰的に完全削除します。取り消し不可。',
      en: 'Recursively deletes files/directories permanently. Cannot be undone.' },
    { pattern: /^rm\s+-[^-]*f/, name: 'rm -f',
      ja: '確認なしでファイルを強制削除します。',
      en: 'Force-deletes files without confirmation.' },
    { pattern: /^sudo\s+rm\b/, name: 'sudo rm',
      ja: 'root権限でファイルを削除します。システムファイルも消える可能性があります。',
      en: 'Deletes files with root privileges. May remove system files.' },
    { pattern: /^rmdir\s+/, name: 'rmdir',
      ja: 'ディレクトリを削除します。',
      en: 'Removes directories.' },

    // --- Git destructive ---
    { pattern: /^git\s+push\s+.*(--force|-f)\b/, name: 'git push --force',
      ja: 'リモートの履歴を強制上書きします。他の人の作業が消える可能性があります。',
      en: 'Force-overwrites remote history. May destroy others\' work.' },
    { pattern: /^git\s+push\s+.*--force-with-lease/, name: 'git push --force-with-lease',
      ja: 'リモートの履歴を条件付きで強制上書きします。',
      en: 'Force-overwrites remote history with safety check.' },
    { pattern: /^git\s+reset\s+--hard/, name: 'git reset --hard',
      ja: 'コミットされていない全ての変更を破棄します。取り消し不可。',
      en: 'Discards all uncommitted changes permanently.' },
    { pattern: /^git\s+clean\s+-[a-z]*f/, name: 'git clean -f',
      ja: '追跡されていないファイルを強制削除します。',
      en: 'Force-deletes untracked files.' },
    { pattern: /^git\s+checkout\s+\.\s*$/, name: 'git checkout .',
      ja: '全ての未コミット変更を破棄します。',
      en: 'Discards all uncommitted changes.' },
    { pattern: /^git\s+restore\s+\.\s*$/, name: 'git restore .',
      ja: '全ての未コミット変更を破棄します。',
      en: 'Discards all uncommitted changes.' },
    { pattern: /^git\s+branch\s+-D\b/, name: 'git branch -D',
      ja: 'ブランチを強制削除します。マージされていない変更が失われます。',
      en: 'Force-deletes a branch. Unmerged changes will be lost.' },
    { pattern: /^git\s+rebase\s+.*--force/, name: 'git rebase --force',
      ja: 'リベースを強制実行します。履歴が書き換わります。',
      en: 'Forces a rebase. Rewrites history.' },

    // --- System-level ---
    { pattern: /^sudo\s+/, name: 'sudo',
      ja: 'root権限でコマンドを実行します。システム全体に影響する可能性があります。',
      en: 'Executes command with root privileges. May affect the entire system.' },
    { pattern: /^chmod\s+.*777/, name: 'chmod 777',
      ja: '全ユーザーにフルアクセス権を付与します。セキュリティリスクがあります。',
      en: 'Grants full access to all users. Security risk.' },
    { pattern: /^chown\s+/, name: 'chown',
      ja: 'ファイルの所有者を変更します。',
      en: 'Changes file ownership.' },
    { pattern: /^mkfs\b/, name: 'mkfs',
      ja: 'ディスクをフォーマットします。全データが消えます。',
      en: 'Formats a disk. All data will be lost.' },
    { pattern: /^dd\s+/, name: 'dd',
      ja: 'ディスクに直接書き込みます。データ破壊の可能性があります。',
      en: 'Writes directly to disk. May destroy data.' },
    { pattern: /^kill\s+-9\b/, name: 'kill -9',
      ja: 'プロセスを即座に強制終了します。データ損失の可能性があります。',
      en: 'Immediately force-kills a process. May cause data loss.' },
    { pattern: /^killall\s+/, name: 'killall',
      ja: '指定した名前の全プロセスを終了します。',
      en: 'Kills all processes with the specified name.' },
    { pattern: /^pkill\s+/, name: 'pkill',
      ja: 'パターンに一致する全プロセスを終了します。',
      en: 'Kills all processes matching the pattern.' },

    // --- Database destructive ---
    { pattern: /DROP\s+(TABLE|DATABASE|SCHEMA|INDEX)/i, name: 'DROP TABLE/DATABASE',
      ja: 'データベースのテーブル/スキーマを削除します。データが全て失われます。',
      en: 'Drops database table/schema. All data will be lost.' },
    { pattern: /TRUNCATE\s+/i, name: 'TRUNCATE',
      ja: 'テーブルの全データを削除します。取り消し不可。',
      en: 'Deletes all data from a table. Cannot be undone.' },
    { pattern: /DELETE\s+FROM\s+\w+\s*$/i, name: 'DELETE without WHERE',
      ja: 'WHERE句なしの全行削除です。テーブルの全データが消えます。',
      en: 'Deletes all rows without WHERE clause.' },
    { pattern: /prisma\s+migrate\s+reset/, name: 'prisma migrate reset',
      ja: 'データベースを完全にリセットします。全データが失われます。',
      en: 'Completely resets the database. All data will be lost.' },

    // --- Network / secrets ---
    { pattern: /curl\s+.*\|\s*(bash|sh|zsh)\b/, name: 'curl | bash',
      ja: 'インターネットからスクリプトをダウンロードして直接実行します。非常に危険です。',
      en: 'Downloads and executes a script from the internet. Very dangerous.' },
    { pattern: /wget\s+.*\|\s*(bash|sh|zsh)\b/, name: 'wget | bash',
      ja: 'インターネットからスクリプトをダウンロードして直接実行します。非常に危険です。',
      en: 'Downloads and executes a script from the internet. Very dangerous.' },

    // --- Docker destructive ---
    { pattern: /^docker\s+system\s+prune\s+-a/, name: 'docker system prune -a',
      ja: '全ての未使用Dockerリソースを削除します。イメージ・コンテナ・ボリューム全て。',
      en: 'Removes all unused Docker resources including images, containers, volumes.' },
    { pattern: /^docker\s+rm\s+-f/, name: 'docker rm -f',
      ja: '実行中のコンテナを強制削除します。',
      en: 'Force-removes running containers.' },
    { pattern: /^docker\s+volume\s+rm/, name: 'docker volume rm',
      ja: 'Dockerボリュームを削除します。永続データが失われます。',
      en: 'Removes Docker volumes. Persistent data will be lost.' },

    // --- Environment ---
    { pattern: />\s*\/etc\//, name: 'write to /etc/',
      ja: 'システム設定ディレクトリに書き込みます。',
      en: 'Writes to system configuration directory.' },
    { pattern: />\s*\/usr\//, name: 'write to /usr/',
      ja: 'システムディレクトリに書き込みます。',
      en: 'Writes to system directory.' },
  ],

  medium: [
    // --- Git operations ---
    { pattern: /^git\s+push\b/, name: 'git push',
      ja: 'リモートリポジトリにコードをプッシュします。他のメンバーに影響します。',
      en: 'Pushes code to remote repository. Affects other team members.' },
    { pattern: /^git\s+commit\b/, name: 'git commit',
      ja: 'ステージされた変更をコミットします。',
      en: 'Commits staged changes.' },
    { pattern: /^git\s+merge\b/, name: 'git merge',
      ja: 'ブランチをマージします。コンフリクトが発生する可能性があります。',
      en: 'Merges branches. May cause conflicts.' },
    { pattern: /^git\s+rebase\b/, name: 'git rebase',
      ja: 'コミット履歴をリベースします。履歴が変更されます。',
      en: 'Rebases commit history. History will be modified.' },
    { pattern: /^git\s+cherry-pick\b/, name: 'git cherry-pick',
      ja: '別ブランチのコミットを取り込みます。',
      en: 'Picks a commit from another branch.' },
    { pattern: /^git\s+stash\s+drop/, name: 'git stash drop',
      ja: 'スタッシュを削除します。保存した変更が失われます。',
      en: 'Drops a stash. Saved changes will be lost.' },
    { pattern: /^git\s+tag\s+-d/, name: 'git tag -d',
      ja: 'タグを削除します。',
      en: 'Deletes a tag.' },
    { pattern: /^git\s+remote\s+(add|remove|set-url)/, name: 'git remote modify',
      ja: 'リモートリポジトリの設定を変更します。',
      en: 'Modifies remote repository configuration.' },

    // --- Package managers ---
    { pattern: /^npm\s+(install|i)\b/, name: 'npm install',
      ja: 'パッケージをインストールします。node_modules と package.json が変更されます。',
      en: 'Installs packages. Modifies node_modules and package.json.' },
    { pattern: /^npm\s+uninstall\b/, name: 'npm uninstall',
      ja: 'パッケージを削除します。package.json が変更されます。',
      en: 'Uninstalls packages. Modifies package.json.' },
    { pattern: /^npm\s+(run\s+)?build\b/, name: 'npm build',
      ja: 'ビルドを実行します。出力ディレクトリが更新されます。',
      en: 'Runs build. Output directory will be updated.' },
    { pattern: /^npm\s+publish\b/, name: 'npm publish',
      ja: 'パッケージをnpmレジストリに公開します。',
      en: 'Publishes package to npm registry.' },
    { pattern: /^npm\s+deprecate\b/, name: 'npm deprecate',
      ja: 'パッケージを非推奨としてマークします。',
      en: 'Marks a package as deprecated.' },
    { pattern: /^npm\s+cache\s+clean/, name: 'npm cache clean',
      ja: 'npmキャッシュを削除します。',
      en: 'Clears npm cache.' },
    { pattern: /^npm\s+update\b/, name: 'npm update',
      ja: 'パッケージをアップデートします。破壊的変更が含まれる可能性があります。',
      en: 'Updates packages. May include breaking changes.' },
    { pattern: /^npx\s+/, name: 'npx',
      ja: 'パッケージをダウンロードして実行します。',
      en: 'Downloads and executes a package.' },

    { pattern: /^yarn\s+(add|install)\b/, name: 'yarn add/install',
      ja: 'パッケージをインストールします。',
      en: 'Installs packages.' },
    { pattern: /^yarn\s+remove\b/, name: 'yarn remove',
      ja: 'パッケージを削除します。',
      en: 'Removes packages.' },

    { pattern: /^pnpm\s+(add|install|i)\b/, name: 'pnpm add/install',
      ja: 'パッケージをインストールします。',
      en: 'Installs packages.' },
    { pattern: /^pnpm\s+remove\b/, name: 'pnpm remove',
      ja: 'パッケージを削除します。',
      en: 'Removes packages.' },

    { pattern: /^bun\s+(add|install|i)\b/, name: 'bun add/install',
      ja: 'パッケージをインストールします。',
      en: 'Installs packages.' },
    { pattern: /^bun\s+remove\b/, name: 'bun remove',
      ja: 'パッケージを削除します。',
      en: 'Removes packages.' },

    // --- pip / Python ---
    { pattern: /^pip\s+install\b/, name: 'pip install',
      ja: 'Pythonパッケージをインストールします。',
      en: 'Installs Python packages.' },
    { pattern: /^pip\s+uninstall\b/, name: 'pip uninstall',
      ja: 'Pythonパッケージを削除します。',
      en: 'Uninstalls Python packages.' },

    // --- Homebrew ---
    { pattern: /^brew\s+(install|uninstall|upgrade)\b/, name: 'brew install/uninstall',
      ja: 'Homebrewでパッケージを変更します。システムに影響します。',
      en: 'Modifies packages via Homebrew. Affects the system.' },

    // --- File operations ---
    { pattern: /^mv\s+/, name: 'mv',
      ja: 'ファイル/ディレクトリを移動またはリネームします。',
      en: 'Moves or renames files/directories.' },
    { pattern: /^cp\s+.*-r/, name: 'cp -r',
      ja: 'ディレクトリを再帰的にコピーします。',
      en: 'Recursively copies directories.' },
    { pattern: /^ln\s+/, name: 'ln',
      ja: 'リンクを作成します。',
      en: 'Creates links.' },
    { pattern: /^mkdir\s+/, name: 'mkdir',
      ja: 'ディレクトリを作成します。',
      en: 'Creates directories.' },
    { pattern: /^touch\s+/, name: 'touch',
      ja: 'ファイルを作成/タイムスタンプを更新します。',
      en: 'Creates files or updates timestamps.' },
    { pattern: /^chmod\s+/, name: 'chmod',
      ja: 'ファイルのパーミッションを変更します。',
      en: 'Changes file permissions.' },

    // --- File writing ---
    { pattern: />\s+\S+/, name: 'file redirect (>)',
      ja: 'ファイルに書き込みます（上書き）。既存の内容は失われます。',
      en: 'Writes to file (overwrite). Existing content will be lost.' },
    { pattern: />>\s+\S+/, name: 'file append (>>)',
      ja: 'ファイルに追記します。',
      en: 'Appends to file.' },
    { pattern: /\btee\s+/, name: 'tee',
      ja: '出力をファイルに書き込みます。',
      en: 'Writes output to file.' },

    // --- sed / awk (file modification) ---
    { pattern: /^sed\s+-i/, name: 'sed -i',
      ja: 'ファイルをインプレースで編集します。',
      en: 'Edits files in-place.' },

    // --- Database operations ---
    { pattern: /^(mysql|psql|sqlite3)\s+/, name: 'database client',
      ja: 'データベースクライアントを起動します。データの変更が可能です。',
      en: 'Starts database client. Can modify data.' },
    { pattern: /prisma\s+migrate\s+dev/, name: 'prisma migrate dev',
      ja: 'マイグレーションを作成・適用します。DBスキーマが変更されます。',
      en: 'Creates and applies migrations. DB schema will change.' },
    { pattern: /prisma\s+db\s+push/, name: 'prisma db push',
      ja: 'スキーマをDBに直接プッシュします（マイグレーションなし）。',
      en: 'Pushes schema directly to DB (without migration).' },
    { pattern: /prisma\s+db\s+seed/, name: 'prisma db seed',
      ja: 'シードデータを投入します。既存データに影響する可能性があります。',
      en: 'Seeds the database. May affect existing data.' },

    // --- Docker operations ---
    { pattern: /^docker\s+build\b/, name: 'docker build',
      ja: 'Dockerイメージをビルドします。',
      en: 'Builds a Docker image.' },
    { pattern: /^docker\s+run\b/, name: 'docker run',
      ja: 'Dockerコンテナを起動します。',
      en: 'Starts a Docker container.' },
    { pattern: /^docker\s+stop\b/, name: 'docker stop',
      ja: 'Dockerコンテナを停止します。',
      en: 'Stops a Docker container.' },
    { pattern: /^docker\s+compose\s+(up|down|restart)/, name: 'docker compose',
      ja: 'Docker Composeでサービスを操作します。',
      en: 'Manages services with Docker Compose.' },
    { pattern: /^docker\s+exec\b/, name: 'docker exec',
      ja: '実行中のコンテナ内でコマンドを実行します。',
      en: 'Executes a command inside a running container.' },

    // --- Network ---
    { pattern: /^curl\s+/, name: 'curl',
      ja: 'HTTP リクエストを送信します。外部サービスと通信します。',
      en: 'Sends HTTP requests. Communicates with external services.' },
    { pattern: /^wget\s+/, name: 'wget',
      ja: 'ファイルをダウンロードします。',
      en: 'Downloads files.' },
    { pattern: /^ssh\s+/, name: 'ssh',
      ja: 'リモートサーバーに接続します。',
      en: 'Connects to a remote server.' },
    { pattern: /^scp\s+/, name: 'scp',
      ja: 'リモートサーバーとファイルを転送します。',
      en: 'Transfers files to/from a remote server.' },

    // --- Process / service ---
    { pattern: /^kill\s+/, name: 'kill',
      ja: 'プロセスにシグナルを送信します。',
      en: 'Sends a signal to a process.' },
    { pattern: /^service\s+/, name: 'service',
      ja: 'システムサービスを操作します。',
      en: 'Manages system services.' },
    { pattern: /^systemctl\s+/, name: 'systemctl',
      ja: 'systemdサービスを操作します。',
      en: 'Manages systemd services.' },
    { pattern: /^launchctl\s+/, name: 'launchctl',
      ja: 'macOSのサービスを操作します。',
      en: 'Manages macOS services.' },

    // --- Environment modification ---
    { pattern: /^export\s+/, name: 'export',
      ja: '環境変数を設定します。',
      en: 'Sets environment variables.' },
    { pattern: /^source\s+/, name: 'source',
      ja: 'シェルスクリプトを現在のシェルで実行します。環境が変更されます。',
      en: 'Executes a shell script in the current shell. Environment will change.' },
    { pattern: /^\.\s+/, name: '. (source)',
      ja: 'シェルスクリプトを現在のシェルで実行します。',
      en: 'Executes a shell script in the current shell.' },

    // --- CI/CD ---
    { pattern: /^gh\s+pr\s+merge\b/, name: 'gh pr merge',
      ja: 'プルリクエストをマージします。',
      en: 'Merges a pull request.' },
    { pattern: /^gh\s+pr\s+close\b/, name: 'gh pr close',
      ja: 'プルリクエストをクローズします。',
      en: 'Closes a pull request.' },
    { pattern: /^gh\s+issue\s+close\b/, name: 'gh issue close',
      ja: 'Issueをクローズします。',
      en: 'Closes an issue.' },
    { pattern: /^gh\s+release\s+create\b/, name: 'gh release create',
      ja: '新しいリリースを作成します。',
      en: 'Creates a new release.' },

    // --- Terraform / IaC ---
    { pattern: /^terraform\s+(apply|destroy)\b/, name: 'terraform apply/destroy',
      ja: 'インフラストラクチャを変更/削除します。',
      en: 'Modifies/destroys infrastructure.' },

    // --- Misc ---
    { pattern: /^crontab\s+-e/, name: 'crontab -e',
      ja: 'cronジョブを編集します。定期実行タスクが変更されます。',
      en: 'Edits cron jobs. Scheduled tasks will change.' },
    { pattern: /^xattr\s+-c/, name: 'xattr -c',
      ja: 'ファイルの拡張属性を全て削除します。',
      en: 'Clears all extended attributes from files.' },
    { pattern: /^defaults\s+write\b/, name: 'defaults write',
      ja: 'macOSのシステム設定を変更します。',
      en: 'Modifies macOS system preferences.' },
    { pattern: /^open\s+-a\b/, name: 'open -a',
      ja: 'アプリケーションを開きます。',
      en: 'Opens an application.' },
  ]
};
